export const columns = {
	general: [
		{ headerName: 'School Name', field: 'schoolName', cellDataType: 'text' },
		{ headerName: 'No of Learners', field: 'noOfLearners', cellDataType: 'number' },
		{ headerName: 'Phase', field: 'phase', cellDataType: 'text' },
		{ headerName: 'Sector', field: 'sector', cellDataType: 'text' },
		{ headerName: 'Lifecycle', field: 'lifecycle', cellDataType: 'text' },
		{ headerName: 'Onboarding Status', field: 'onboardingStatus', cellDataType: 'text' },
		{ headerName: 'Current Status', field: 'currentStatus', cellDataType: 'text' },
		{ headerName: 'Next Activity', field: 'nextActivity', cellDataType: 'text' },
		{ headerName: 'Next Appointment', field: 'nextAppointment', cellDataType: 'dateString' },
		{ headerName: 'Circuit', field: 'circuit', cellDataType: 'text' },
		{ headerName: 'School Website', field: 'schoolWebsite', cellDataType: 'text' },
	],
	marketingActivities: [
		{ headerName: 'School/Principal Pain-point', field: 'schoolPrincipalPainPoint', cellDataType: 'text' },
		{ headerName: 'Special Request', field: 'specialRequest', cellDataType: 'text' },
		{ headerName: 'Special Request Date', field: 'specialRequestDate', cellDataType: 'dateString' },
		{ headerName: 'Stopper', field: 'stopper', cellDataType: 'text' },
		{ headerName: 'Support Required', field: 'supportRequired', cellDataType: 'text' },
		{ headerName: 'Lessons Learnt', field: 'lessonsLearnt', cellDataType: 'text' },
		{
			headerName: 'Subscription Offer Signature Date',
			field: 'subscriptionOfferSgnatureDate',
			cellDataType: 'dateString',
		},
	],
	attractionActivities: [
		{ headerName: 'First Date of Engaging School', field: 'firstDateOfEngagingSchool', cellDataType: 'dateString' },
		{ headerName: 'Principal Buy-In', field: 'principalBuyIn', cellDataType: 'text' },
		{ headerName: 'SGB Presentation', field: 'sgbPresentation', cellDataType: 'text' },
		{ headerName: 'Finance Documentation', field: 'financeDocumentation', cellDataType: 'text' },
		{ headerName: 'School Data', field: 'schoolData', cellDataType: 'text' },
		{ headerName: 'SMT Engagement', field: 'smtEngagement', cellDataType: 'text' },
		{ headerName: 'ICT Champion Demo', field: 'ictChampionDemo', cellDataType: 'text' },
		{ headerName: 'Educator Presentation', field: 'educatorPresentation', cellDataType: 'text' },
		{ headerName: 'Parent Flyer', field: 'parentFlyer', cellDataType: 'text' },
		{ headerName: 'Parent Onboarding', field: 'parentOnboarding', cellDataType: 'text' },
		{ headerName: 'Weekly Onboarding', field: 'weeklyOnboarding', cellDataType: 'text' },
		{ headerName: 'Onboarding Closure Date', field: 'onboardingClosureDate', cellDataType: 'dateString' },
	],
	schoolAddressInfo: [
		{ headerName: 'School EMIS', field: 'schoolEmis', cellDataType: 'text' },
		{ headerName: 'School Phone No', field: 'schoolPhoneNo', cellDataType: 'text' },
		{ headerName: 'School Alternate Phone', field: 'schoolAlternatePhone', cellDataType: 'text' },
		{ headerName: 'School Email', field: 'schoolEmail', cellDataType: 'text' },
		{ headerName: 'Street Address', field: 'streetAddress', cellDataType: 'text' },
		{ headerName: 'Postal Address', field: 'postalAddress', cellDataType: 'text' },
		{ headerName: 'Suburb', field: 'suburb', cellDataType: 'text' },
		{ headerName: 'Town/City', field: 'townCity', cellDataType: 'text' },
		{ headerName: 'Postal Code', field: 'postalCode', cellDataType: 'text' },
		{ headerName: 'Municipality', field: 'municipality', cellDataType: 'text' },
		{ headerName: 'Circuit', field: 'circuitName', cellDataType: 'text' },
		{ headerName: 'District', field: 'districtName', cellDataType: 'text' },
		{ headerName: 'Quintile', field: 'quintile', cellDataType: 'text' },
		{ headerName: 'Address Info Comment', field: 'addressInfoComment', cellDataType: 'text' },
	],
	schoolPrincipalInfo: [
		{ headerName: 'Principal Name', field: 'principalName', cellDataType: 'text' },
		{ headerName: 'Principal Mobile 1', field: 'principalMobile', cellDataType: 'text' },
		{ headerName: 'Principal Alternate Mobile', field: 'principalAlternateMobile', cellDataType: 'text' },
		{ headerName: 'Principal Email Address', field: 'principalEmailAddress', cellDataType: 'text' },
		{ headerName: 'Billing Contact Name', field: 'billingContactName', cellDataType: 'text' },
		{ headerName: 'Billing Contact Phone Number', field: 'billingContactPhoneNumber', cellDataType: 'text' },
		{ headerName: 'Billing Contact Designation', field: 'billingContactDesignation', cellDataType: 'text' },
		{ headerName: 'Billing Email Address', field: 'billingEmailAddress', cellDataType: 'text' },
		{ headerName: 'Billing Date', field: 'billingDate', cellDataType: 'dateString' },
	],
	otherStakeholdersInfo: [
		{ headerName: 'SGB Chairperson Name', field: 'sgbChairpersonName', cellDataType: 'text' },
		{ headerName: 'SGB Chairperson Phone', field: 'sgbChairpersonPhone', cellDataType: 'text' },
		{ headerName: 'SGB Chairperson Email', field: 'sgbChairpersonEmail', cellDataType: 'text' },
		{ headerName: 'Additional Contact 1 Name', field: 'additionalContact1Name', cellDataType: 'text' },
		{ headerName: 'Additional Contact 1 Designation', field: 'additionalContact1Designation', cellDataType: 'text' },
		{ headerName: 'Additional Contact 1 Mobile', field: 'additionalContact1Mobile', cellDataType: 'text' },
		{ headerName: 'Additional Contact 1 Email', field: 'additionalContact1Email', cellDataType: 'text' },
		{ headerName: 'Additional Contact 2 Name', field: 'additionalContact2Name', cellDataType: 'text' },
		{ headerName: 'Additional Contact 2 Designation', field: 'additionalContact2Designation', cellDataType: 'text' },
		{ headerName: 'Additional Contact 2 Mobile', field: 'additionalContact2Mobile', cellDataType: 'text' },
		{ headerName: 'Additional Contact 2 Email', field: 'additionalContact2Email', cellDataType: 'text' },
		{ headerName: 'Stakeholder Info Comment', field: 'stakeholderInfoComment', cellDataType: 'text' },
	],
	schoolValueStatements: [
		{ headerName: 'School Slogan', field: 'schoolSlogan', cellDataType: 'text' },
		{ headerName: 'School Mission', field: 'schoolMission', cellDataType: 'text' },
		{ headerName: 'School Vision', field: 'schoolVision', cellDataType: 'text' },
		{ headerName: 'School Values', field: 'schoolValues', cellDataType: 'text' },
		{ headerName: 'School Logo', field: 'schoolLogo', cellDataType: 'text' },
		{ headerName: 'School Gallery photos', field: 'schoolGalleryPhotos', cellDataType: 'text' },
		{ headerName: 'School Videos', field: 'schoolVideos', cellDataType: 'text' },
	],
	engagementActivities: [
		{ headerName: 'School Photo Data', field: 'schoolPhotoDataStatus', cellDataType: 'text' },
		{ headerName: 'Meeting - SGB Chairperson', field: 'meetingSgbChairpersonStatus', cellDataType: 'text' },
		{ headerName: 'Meeting - SGB FinCom/Treasurer', field: 'meetingSgbFinComTreasurerStatus', cellDataType: 'text' },
		{ headerName: 'Principal Trainings', field: 'principalTrainingsStatus', cellDataType: 'text' },
		{ headerName: 'ICT Trainings', field: 'ictTrainingsStatus', cellDataType: 'text' },
		{ headerName: 'Timetable Type', field: 'timetableTypeStatus', cellDataType: 'text' },
		{ headerName: 'Upload Timetable', field: 'uploadTimetableStatus', cellDataType: 'text' },
		{ headerName: 'School Values', field: 'schoolValuesStatus', cellDataType: 'text' },
	],
	salesDocumentation: [
		{ headerName: '1st Quotation Date', field: 'firstQuotationDate', cellDataType: 'dateString' },
		{ headerName: 'Quotation', field: 'quotation', cellDataType: 'text' },
		{ headerName: 'Subscription Agreement', field: 'subscriptionAgreement', cellDataType: 'text' },
		{ headerName: 'Purchase Order', field: 'purchaseOrder', cellDataType: 'text' },
		{ headerName: 'Invoice', field: 'invoice', cellDataType: 'text' },
		{ headerName: '1st Payment Date', field: 'firstPaymentDate', cellDataType: 'dateString' },
		{ headerName: '1st Invoice Date', field: 'firstInvoiceDate', cellDataType: 'dateString' },
	],
	fieldTechnicalChecklist: [
		{ headerName: 'CRM - School Info', field: 'crmSchoolInfoStatus', cellDataType: 'text' },
		{ headerName: 'CRM - Principal Info', field: 'crmPrincipalInfoStatus', cellDataType: 'text' },
		{ headerName: 'CRM - ICT Committee', field: 'crmIctCommitteeStatus', cellDataType: 'text' },
		{ headerName: 'School URL', field: 'schoolUrlStatus', cellDataType: 'text' },
		{ headerName: 'School Logo', field: 'schoolLogoStatus', cellDataType: 'text' },
		{ headerName: 'School Photos', field: 'schoolPhotosStatus', cellDataType: 'text' },
		{ headerName: 'School Data', field: 'schoolDataStatus', cellDataType: 'text' },
		{ headerName: 'School Timetable', field: 'schoolTimetableStatus', cellDataType: 'text' },
		{ headerName: 'School Gallery', field: 'schoolGalleryStatus', cellDataType: 'text' },
		{ headerName: 'School Uniform', field: 'schoolUniformStatus', cellDataType: 'text' },
		{ headerName: 'School Bookstore', field: 'schoolBookstoreStatus', cellDataType: 'text' },
		{ headerName: 'School Event Calendar', field: 'schoolEventCalendarStatus', cellDataType: 'text' },
		{ headerName: 'SMS Logins to Educators', field: 'smsLoginsToEducatorsStatus', cellDataType: 'text' },
		{ headerName: 'Parent Flyers printing', field: 'parentFlyersPrintingStatus', cellDataType: 'text' },
	],
	remoteTechnicalCheckList: [
		{ headerName: 'Staging Started', field: 'stagingStarted', cellDataType: 'dateString' },
		{ headerName: 'Buy Domain', field: 'buyDomain', cellDataType: 'text' },
		{ headerName: 'Cloud Flare', field: 'cloudFlare', cellDataType: 'text' },
		{ headerName: 'Re-captcha', field: 'reCaptcha', cellDataType: 'text' },
		{ headerName: 'Website mode', field: 'websiteMode', cellDataType: 'text' },
		{ headerName: 'School Assets', field: 'schoolAssets', cellDataType: 'text' },
		{ headerName: 'School Data staging', field: 'schoolDataStaging', cellDataType: 'text' },
		{ headerName: 'Upload School Data', field: 'uploadSchoolData', cellDataType: 'text' },
		{ headerName: 'Role Management', field: 'roleManagement', cellDataType: 'text' },
		{ headerName: 'ICT Champion Admin', field: 'ictChampionAdmin', cellDataType: 'text' },
		{ headerName: 'ICT Champion Login', field: 'ictChampionLogin', cellDataType: 'text' },
		{ headerName: 'School Resources', field: 'schoolResources', cellDataType: 'text' },
		{ headerName: 'SEO', field: 'seo', cellDataType: 'text' },
		{ headerName: 'Google Maps', field: 'googleMaps', cellDataType: 'text' },
		{ headerName: 'Favicon', field: 'favicon', cellDataType: 'text' },
		{ headerName: 'Homepage Logo', field: 'homepageLogo', cellDataType: 'text' },
		{ headerName: 'District Logo', field: 'districtLogo', cellDataType: 'text' },
		{ headerName: 'Metadata', field: 'metadata', cellDataType: 'text' },
		{ headerName: 'School Readiness Completed', field: 'schoolReadinessCompleted', cellDataType: 'dateString' },
	],
	moduleTesting: [
		{ headerName: 'Learner Search', field: 'learnerSearch', cellDataType: 'text' },
		{ headerName: 'Attendance Register', field: 'attendanceRegister', cellDataType: 'text' },
		{ headerName: 'Mobile Push Notification', field: 'mobilePushNotification', cellDataType: 'text' },
		{ headerName: 'Notification Groups & Management', field: 'notificationGroupsManagement', cellDataType: 'text' },
		{ headerName: 'Digital Content', field: 'digitalContent', cellDataType: 'text' },
		{ headerName: 'Timetable', field: 'timetable', cellDataType: 'text' },
		{ headerName: 'School Notice', field: 'schoolNotice', cellDataType: 'text' },
		{ headerName: 'Merit/Demerit', field: 'meritDemerit', cellDataType: 'text' },
		{ headerName: 'Banner Management', field: 'bannerManagement', cellDataType: 'text' },
		{ headerName: 'Campaign Management', field: 'campaignManagement', cellDataType: 'text' },
		{ headerName: 'Our School', field: 'ourSchool', cellDataType: 'text' },
		{ headerName: 'Academic Calendar', field: 'academicCalendar', cellDataType: 'text' },
		{ headerName: 'Event Management', field: 'eventManagement', cellDataType: 'text' },
		{ headerName: 'Outstanding Items/Comments', field: 'outstandingItemsComments', cellDataType: 'text' },
	],
	backendTasks: [
		{ headerName: 'School-Link - Onelink', field: 'schoolLinkOnelink', cellDataType: 'text' },
		{ headerName: 'School-Link - Playstore', field: 'schoolLinkPlaystore', cellDataType: 'text' },
		{ headerName: 'School-Link - Applestore', field: 'schoolLinkApplestore', cellDataType: 'text' },
		{ headerName: 'School-Link - Huawei Gallery', field: 'schoolLinkHuaweiGallery', cellDataType: 'text' },
		{ headerName: 'App Store Version', field: 'appStoreVersion', cellDataType: 'text' },
		{ headerName: 'Website Version', field: 'websiteVersion', cellDataType: 'text' },
		{ headerName: 'Server Name', field: 'serverName', cellDataType: 'text' },
		{ headerName: 'Server No', field: 'serverNo', cellDataType: 'text' },
		{ headerName: 'School Status', field: 'schoolStatus', cellDataType: 'text' },
		{ headerName: 'School Status Date', field: 'schoolStatusDate', cellDataType: 'dateString' },
		{ headerName: 'App Platform', field: 'appPlatform', cellDataType: 'text' },
		{ headerName: 'District', field: 'district', cellDataType: 'text' },
		{ headerName: 'School Systems Internal ID', field: 'schoolSystemsInternalId', cellDataType: 'text' },
	],
}

export const allColumnsWithHeader = [
	{
		headerName: 'General',
		children: columns.general,
	},
	{
		headerName: 'Marketing Activities',
		children: columns.marketingActivities,
	},
	{
		headerName: 'Attraction Activities',
		children: columns.attractionActivities,
	},
	{
		headerName: 'School Address Info',
		children: columns.schoolAddressInfo,
	},
	{
		headerName: 'School Principal Info',
		children: columns.schoolPrincipalInfo,
	},
	{
		headerName: 'Other Stakeholders Info',
		children: columns.otherStakeholdersInfo,
	},
	{
		headerName: 'School Values Statements',
		children: columns.schoolValueStatements,
	},
	{
		headerName: 'Engagement Activities',
		children: columns.engagementActivities,
	},
	{
		headerName: 'Sales Documentation',
		children: columns.salesDocumentation,
	},
	{
		headerName: 'Field Technical Checklist',
		children: columns.fieldTechnicalChecklist,
	},
	{
		headerName: 'Remote Technical Checklist',
		children: columns.remoteTechnicalCheckList,
	},
	{
		headerName: 'Module Testing',
		children: columns.moduleTesting,
	},
	{
		headerName: 'Backend Tasks',
		children: columns.backendTasks,
	},
]

export const defaultColumns = [
	{
		headerName: 'General',
		children: [
			{ headerName: 'School Name', field: 'schoolName', cellDataType: 'text' },
			{ headerName: 'No of Learners', field: 'noOfLearners', cellDataType: 'number' },
			{ headerName: 'Phase', field: 'phase', cellDataType: 'text' },
			{ headerName: 'School Website', field: 'schoolWebsite', cellDataType: 'text' },
		],
	},
	{
		headerName: 'Attraction Activities',
		children: [
			{ headerName: 'School Data', field: 'schoolData', cellDataType: 'text' },
			{ headerName: 'Parent Flyer', field: 'parentFlyer', cellDataType: 'text' },
		],
	},
	{
		headerName: 'School Address Info',
		children: [
			{ headerName: 'Circuit', field: 'circuit', cellDataType: 'text' },
			{ headerName: 'District', field: 'district', cellDataType: 'text' },
		],
	},
	{
		headerName: 'Remote Technical Checklist',
		children: [{ headerName: 'School Data staging', field: 'schoolDataStaging', cellDataType: 'text' }],
	},
	{
		headerName: 'Backend Tasks',
		children: [{ headerName: 'Server Name', field: 'serverName', cellDataType: 'text' }],
	},
]
